
# datacube environments and the corresponding list of product names
datacubes:
- dev: ['wofs_filtered_summary',  ]
- prod: ['wofs_summary']
- wofs_confidence: ['mrvbf_nc', 'modis_nc', 'urban_areas_nc', 'dsm_albers',]
- wofsanc: []
- mock: []

# the variables or factors used in the confidence model
factors:
- {name: 'mrvbf', product: 'mrvbf', band: 'band1'}
- {name: 'modis', product: 'modis', band: 'band1'}
- {name: 'urbanareas', product: 'urban_areas', band: 'band1'}
- {name: 'slope', product: 'dsm', band: 'slope'}
- {name: 'clearobs', product: 'wofs_summary', band: 'count-clear'}
- {name: 'phat', product: 'wofs_summary', band: 'frequency'}

# Wofs filtered summary layer to band mappings
wofs_filtered_summary:
  confidence: 'confidence'
  confidence_filtered: 'confidence_filtered'
  filename: 'wofs_filtered_summary_{}_{}.nc'
  filtered_summary_dir: '/g/data/u46/users/aj9439/wofs/data'

# storage
storage:
  driver: NetCDF CF

  crs: EPSG:3577
  tile_size:
      x: 100000.0
      y: 100000.0
  resolution:
      x: 25
      y: -25
  chunking:
      x: 200
      y: 200
      time: 1
  dimension_order: [time, y, x]

# Pre processing
thresholds_and_bounds:
  phat: 0.0
  mrvbf: 10.0
  modis: 100.0

# Confidence filtering
confidence_filtering:
  trained_model_path: '/g/data/u46/wofs/confidence_albers/tmp/confidence_model.pkl'
  threshold: 0.1

# coverage
coverage:
  tile_list_path: '/home/547/aj9439/PycharmProjects/wofs-confidence/configs/temp_tile_list'

logs:
# a sub directory of the working directory. Futher sub-directories are maintained for
# each major processing step
  path: ./logs
  level: INFO

global_attributes:
  title: Water Observations from Space Filtered Statistics 2.1.5
  summary: |
      In previous versions of WOfS, the basic water classifications, statistical summaries
      and confidence products were contained within one product with several datasets. As of
      version 2.1.5, WOfS is split into three products: Water Observation Feature Layers
      (WO_25_2.1.5), Summary Statistics (WO-STATS_25_2.1.5), and Filtered Summary Statistics
      (WO-FILT-STATS_25_2.1.5).

      This product is Water Observations from Space - Filtered Statistics (WO-FILT-STATS),
      consisting of a Confidence layer that compares the WO-STATS water summary to other
      national water datasets, and the Filtered Water Summary which uses the Confidence to
      mask areas of the WO-STATS water summary where Confidence is low. The Filtered Water
      Summary provides the long term understanding of the recurrence of water in the
      landscape, with much of the noise due to misclassification filtered out.

      WO-FILT-STATS consists of the following datasets:
      Confidence: the degree of agreement between water shown in the Water Summary
      and other national datasets. The Confidence layer provides understanding of
      whether the water shown in the Water Summary agrees with where water should
      exist in the landscape, such as due to sloping land or whether water has been
      detected in a location by other means.
      Filtered Water Summary: A simplified version of the Water Summary, showing the
      frequency of water observations where the Confidence is above a cutoff level.
      This layer gives a noise-reduced view of surface water across Australia.

      Even though confidence filtering is applied to the Filtered Water Summary, some cloud
      and shadow, and sensor noise does persist.
  source: "Water Observation from Space Detection Algorithm v1.2"
  cmi_id: wo-filt-stats_25_2.1.5
  institution: Commonwealth of Australia (Geoscience Australia)
  keywords: AU/GA,NASA/GSFC/SED/ESD/LANDSAT,ETM+,TM,OLI,EARTH SCIENCE,SURFACE WATER,FLOOD
  keywords_vocabulary: GCMD
  product_version: 2.1.5
  product_suite: Water Observations from Space 25m
  publisher_email: earth.observation@ga.gov.au
  publisher_name: Section Leader, Operations Section, NEMO, Geoscience Australia
  publisher_url: http://www.ga.gov.au
  license: CC BY Attribution 4.0 International License
  cdm_data_type: Grid
  references: |
       N. Mueller, A. Lewis, D. Roberts, S. Ring, R. Melrose, J. Sixsmith, L. Lymburner, A. McIntyre, P. Tan, S. Curnow, A. Ip, Water observations from space: Mapping surface water from 25 years of Landsat imagery across Australia, Remote Sensing of Environment, Volume 174, 1 March 2016, Pages 341-352, ISSN 0034-4257, http://dx.doi.org/10.1016/j.rse.2015.11.003. (http://www.sciencedirect.com/science/article/pii/S0034425715301929)
