# A unique identifier is assigned to each WOfS run.
base_dir: ${base_dir}
run_id: ${run_id}
description: ${run_desc}


# All WOfS programs use the working_dirctory as the "present working directory"
# All logging and temporary files go to this directory as do the key WOfS output product
# The policy is to use /g/data/u46/wofs as the base for WOfS working directory
# The run_id is incorporated into the working directory name to allow different runs to be
# clearly delineated.
working_dir: '{base_dir}s/water_{run_id}s'

# scratch_dir refers to the directory where WOfS writes all intermediate result files
#
# WOfS generates large numbers of scratch files and deletes them when they are no
# longer required by the workflow. Placing the scratch directory in the working_dir
# ensures that WOfS runs are fully re-runnable (WOfS will reuse exsiting intermediate
# files in the scratch area to resume processing when a Luigi job is resubmitted.
#
# setting scratch_dir to the empty string will result in the scratch directory being created
# on PBS_JOBFS or /tmp file system. Whilst this may prove to be more efficient for some
# processing (short, incremental WoFS updates) it is not recommended for full
# continental runs involving the whole continent. Handle this parameter with care!

# scratch_dir =
scratch_dir: '{working_dir}s/scratch'

# All logging is controlled by the ``logging.cfg`` file which is copied to the working
# directory from source for each run. The ``logging.cfg`` file may be amended before each
# run or step within a run. Log files are copied to the following directory by PBS scripts

logs_dir: '{working_dir}s/logs'

# The Image Pyramids which form one of the may outputs of WOfS are written to the
# following directory during the 'wofs_pyramids' stage of processing

pyramids_dir: '{working_dir}s/pyramids'

# output from a WOfS audit process is placed here

audit_dir: '{working_dir}s/audit'

# Pixels which have a solar incident to terrain angle less that than the
# specified value are masked out. The value is in degrees to the terrain tangent plane

low_solar_incident_threshold: 30

# Pixels where the DSM indicates a high slope are masked out. The limit value is in degrees
# to horizontal

slope_limit_degrees: 12.0

# fuzzy_secs allows for some variation in the timestamp associated with Datacube tiles
# Timestamps within the 'fuzzy_sec' time interval are deemed to be identical
# time window for water extents (in seconds)

extent_tile_fuzzy_secs: 10

# time window for shadow and solar incident tiles (in decimal years)
# 30 minutes = .5 / 24 / 365.24 = 5.704011974e-5

shadow_tile_fuzzy_delta: 5.704011974e-5


# confidence data
confidence_data:
#phat_pmin_dir = %(working_dir)s/confidence/pmin
#factor_dir = %(base_dir)s/confidence
#training_cells_dir=%(base_dir)s/confidence/Training
#mrvbf_dir = %(base_dir)s/confidence/MrVBF
#geoFabric_dir = %(base_dir)s/confidence/geoFabric
#urbanAreas_dir = %(base_dir)s/confidence/urbanAreas
#modis_dir = %(base_dir)s/confidence/modis
#confidence_factors = mrvbf,modis,slope,phat,geofabric_canal,geofabric_foreshore,geofabric_pondage,geofabric_reservoir,geofabric_flat,geofabric_lake,geofabric_rapid,geofabric_swamp,geofabric_watercourse,urbanareas
#GEOFABRIC = unclassified,canal,flat,foreshore,pondage,rapid,watercourse,lake,reservoir,swamp
#
#geofabric_tile = %(geoFabric_dir)s/tiles/GEOFABRIC_%%s.tif
#urbanArea_tile = %(urbanAreas_dir)s/tiles/'ABSDATA_%%s.tif
#mrvbf_tile =

# datacube environments and the corresponding list of product names
datacubes:
- default: ['wofs_albers', 'wofs_confidence']
- wofs: ['mrvbf', 'modis', 'geo_fabric', 'urban_area']

# the variables or factors used in the confidence model
factors:
- {name: 'mrvbf', product: 'mrvbf', band: '1'}
- {name: 'cloud', product: 'wofs_albers', band: 'water', flag: 'cloud'}
- {name: 'wet', product: 'wofs_albers', band: 'water', flag: 'wet'}

# confidence processing
confidence_processing:
  phat_confidence: 90.0
  training_C: 1.0
  training_penalty: l2
  confidence_threshold: 1.0

# confidence outputs
confidence_outputs:
  confidence_base_dir: '{working_dir}s/confidence'
  trained_model_path: '{confidence_base_dir}s/model/confidence_model.pkl'
  confidence_output_dir: '{confidence_base_dir}s/tiles'

# The following specifies the temporal and spatial coverage for this WOfS run together with which
# satellites are to be processed

coverage:
#lat_min_deg = -45
#lat_max_deg = -4
#lon_min_deg = 111
#lon_max_deg = 154
  start_datetime: 1960-01-01T00:00:00.0Z
  end_datetime: 2020-01-01T00:00:00.0Z
  satellites: LS5,LS7,LS8

# list of cells to exclude from processing
# exclude_cells=[[150,-33],[150,-34]]

# list of cells to include. If this list is empty or the parameter absent, ALL datacube cells within
# the bounds of the coverage are included.
# The following are WOfS test cells

# include_cells=[[115,-32],[119,-25],[122,-33],[124,-28],[132,-13],[132,-23],[137,-28],[139,-25],[139,-31],[142,-16],[142,-32],[143,-36],[144,-38],[145,-17],[146,-43],[147,-37],[149,-35],[149,-36],[150,-27],[150,-34],[139,-36],[139,-37],[139,-38],[140,-36],[140,-37],[140,-38],[140,-39],[130,-13],[144,-39],[145,-39],[153,-28],[123,-17],[123,-18],[146,-39],[149,-38],[121,-29],[142,-22],[118,-23],[146,-34],[135,-18]]

logs:
# a sub directory of the working directory. Futher sub-directories are maintained for
# each major processing step
  path: ./logs
  level: INFO

core:
  logging_conf_file: '{base_dir}/water_{run_id}/logging.cfg'


inputs:
# a sub directory of the working directory containing:
#   - tiles.csv               -- contains all tiles selected from the datacube
#   - cell_tiles_150_-034.csv -- contains tiles for one cell
  path: ./inputs

shadows:
# A shadow mask is created for each NBAR tile being processed by WOfS. Each shadow mask
# contains two bands, 1. The solar incident angle to terrain and 2. The cast shadow state
# for the pixel (in shade, true/false). The creation of a shadow mask is very expensive
# so WOfS caches each mask to a directory reuse in later WOfS runs. The path below points
# to that directory containing shadow masks organised into
# "cell subdirectories". e.g. ./shadows/150_-034 contains shadow mask geotiffs
# for cell 150_-034 -- one shadow mask per NBAR scene being processed
  path: /g/data/u46/wofs/shadows
# To create a shadow mask for each NBAR tile, WOfS requires a DSM tils with a 250 pixel
# border. The border prevents edge effects during ray tracing computation. Assembling
# a bordered DSM tile is computationally expensive so, once created, these tiles are
# stored permanenty (for later reuse) in the directory below.
  bordered_dsm_tile_path: /g/data/u46/wofs/bordered_dsm
# path to directory containing DSM tiles. File this directory have the format
# DSM_<long>_<lat>.tif
  dsm_path: /g/data/rq6/DSM/EPSG4326_1deg_0.00025pixel/dsm1sv1_0_Clean.img