
# datacube environments and the corresponding list of product names
datacubes:
- dev: ['wofs_summary_filtered', 'wofs_statistical_summary', 'mrvbf', 'modis', 'urban_areas', 'dsm']
- wofs_confidence: []
- mock: []

# the variables or factors used in the confidence model
factors:
- {name: 'mrvbf', product: 'mrvbf', band: 'band1'}
- {name: 'modis', product: 'modis', band: 'band1'}
- {name: 'urbanareas', product: 'urban_areas', band: 'band1'}
- {name: 'slope', product: 'dsm', band: 'slope'}
- {name: 'clearobs', product: 'wofs_statistical_summary', band: 'count-clear'}
- {name: 'phat', product: 'wofs_statistical_summary', band: 'frequency'}

# Wofs filtered summary layer to band mappings
wofs_filtered_summary:
  confidence: 'confidence'
  confidence_filtered: 'confidence_filtered'
  filename: 'wofs_filtered_summary_{}_{}.nc'
  filtered_summary_dir: '/g/data/u46/users/aj9439/wofs/data'

# storage
storage:
  driver: NetCDF CF

  crs: EPSG:3577
  tile_size:
      x: 100000.0
      y: 100000.0
  resolution:
      x: 25
      y: -25
  chunking:
      x: 200
      y: 200
      time: 1
  dimension_order: [time, y, x]

# Pre processing
thresholds_and_bounds:
  phat: 0.0
  mrvbf: 10.0
  modis: 100.0

# Confidence filtering
confidence_filtering:
  trained_model_path: '/g/data/u46/wofs/confidence_albers/tmp/confidence_model.pkl'
  threshold: 0.1

# coverage
coverage:
  tile_list_path: '/home/547/aj9439/PycharmProjects/wofs-confidence/configs/temp_tile_list'

logs:
# a sub directory of the working directory. Futher sub-directories are maintained for
# each major processing step
  path: ./logs
  level: INFO
